config/routes.rb
Railsgoat::Application.routes.draw do

  get "login" => "sessions#new"
  get "signup" => "users#new"
  get "logout" => "sessions#destroy"
  match "forgot_password" => "password_resets#forgot_password"
  get "password_resets" => "password_resets#confirm_token"
  post "password_resets" => "password_resets#reset_password"
  get "dashboard/doc" => "dashboard#doc"

  resources :sessions do
  end

  resources :users do
    get "account_settings"

    resources :retirement do
    end

    resources :paid_time_off do
    end

    resources :work_info do
    end

    resources :performance do

    end

    resources :benefit_forms do

    end

    resources :messages do
    end

    resources :pay do
      collection do
        post "update_dd_info"
        post "decrypted_bank_acct_num"
      end
    end

  end

  get "download" => "benefit_forms#download"
  post "upload" => "benefit_forms#upload"

  resources :tutorials do
    collection do
      get "credentials"
    end
  end

  resources :schedule do
    collection do
      get "get_pto_schedule"
    end

  end

  resources :admin do
    get "dashboard"
    get "get_user"
    post "delete_user"
    put "update_user"
    get "get_all_users"
    get "analytics"
  end

  resources :dashboard do
    collection do
      get "home"
      get "change_graph"
    end
  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
        resources :users
        resources :mobile
    end
   end


  root :to => "sessions#new"

end

app/views/layouts/shared/_footer.html.erb
<footer>
  <p align="center">
    &copy; The Open Web Application Security Project - OWASP, 2015
  </p>
</footer>

 <script type="text/javascript">

 //ScrollUp
  $(function () {
    $.scrollUp({
      scrollName: 'scrollUp', // Element ID
      topDistance: '300', // Distance from top before showing element (px)
      topSpeed: 300, // Speed back to top (ms)
      animation: 'fade', // Fade, slide, none
      animationInSpeed: 400, // Animation in speed (ms)
      animationOutSpeed: 400, // Animation out speed (ms)
      scrollText: 'Scroll to top', // Text for element
      activeOverlay: false, // Set CSS color to display scrollUp active point, e.g '#00FFFF'
    });
  });
</script>

app/views/layouts/shared/_header.html.erb
<% if current_user %>
  <header>
      <span style="color:#eee;margin-left:10px;">
        Font Size:
        <a href="<%= home_dashboard_index_path %>?font=8pt" style="font-size:10pt;color:#eee;">A</a>
        <a href="<%= home_dashboard_index_path %>?font=200%25" style="font-size:18pt;color:#eee;">A</a>
      </span>
      <div class="user-profile">
        <a data-toggle="dropdown" class="dropdown-toggle">
          <img src=" <%= image_path('profile_color.jpg')%>"  alt="profile">
        </a>
        <span class="caret"></span>
        <ul class="dropdown-menu pull-right">
          <li>
           <%= link_to "account settings", user_account_settings_path(:user_id => current_user.user_id) %>
          </li>
          <li>
            <%= link_to "logout", logout_path %>
          </li>
        </ul>
      </div>
      <ul class="mini-nav">
       <li style="color: #FFFFFF">
          <!--
          I'm going to use HTML safe because we had some weird stuff
          going on with funny chars and jquery, plus it says safe so I'm guessing
          nothing bad will happen
          -->
          Welcome, <%= current_user.first_name.html_safe %>
       </li>
      </ul>
      <ul class="mini-nav">
        <li>
          <%= button_to "Visit Tutorial", "https://github.com/OWASP/railsgoat/wiki/tutorials", {:class => "btn", :method => "get"} %>
        </li>
      </ul>
  </header>
<% else %>
  <!-- Want to use this template whether auth'd or not so I've got some code to determine how to render below -->
  <header>
      <ul class="mini-nav">
           <li>
             <%= button_to "signup", signup_path, {:class => "btn btn-primary", :method => "get"} %>
           </li>
         </ul>
      <ul class="mini-nav">
           <li>
             <%= button_to "login", login_path, {:class => "btn", :method => "get"} %>
           </li>
         </ul>
      <ul class="mini-nav">
           <li>
             <%= button_to "Tutorial Credentials", "#myModalLabel1", {:id => "show_creds_btn", :class => "btn btn-danger", :method => "get"} %>
           </li>
      </ul>
      <ul class="mini-nav">
        <li>
          <%= button_to "Visit Tutorial", "https://github.com/OWASP/railsgoat/wiki/tutorials", {:class => "btn", :method => "get"} %>
        </li>
      </ul>
  </header>
  
  <div id="modal_div" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myAlert" aria-hidden="true">
  </div>

<script type="text/javascript">

$('#show_creds_btn').click(function(event) {
  event.preventDefault();
  $("#modal_div").load(<%= credentials_tutorials_path.inspect.html_safe %>);
  $("#modal_div").modal("show");
});
</script>

<% end %>

app/views/layouts/shared/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if name == :error %>
    <div class="alert alert-error">
      <a class="close" data-dismiss="alert" href="#">×</a>
          <%= content_tag :div, msg, :id => "flash_notice" %>
    </div>
  <% elsif name == :success %>
    <div class="alert alert-success">
      <a class="close" data-dismiss="alert" href="#">×</a>
          <%= content_tag :div, msg, :id => "flash_notice" %>
    </div>
  <% elsif name == :info %>
    <div class="alert alert-info">
      <a class="close" data-dismiss="alert" href="#">×</a>
        <%= content_tag :div, msg, :id => "flash_notice" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/shared/_sidebar.html.erb
<% if current_user %>
    <div id="mainnav" class="hidden-phone hidden-tablet">
      <ul style="display: block;">
        <li id="home">
          <%= link_to home_dashboard_index_path do %>
            <div class="icon">
              <span class="fs1" aria-hidden="true" data-icon="&#xe0a0;"></span>
            </div>
            Dashboard
          <% end %>
        </li>
        <% if is_admin? %>
        	<li class="submenu" id='admin'>
        	   <a href="#">
        	    <div class="icon">
        	      <span class="fs1" aria-hidden="true" data-icon="&#xe1c8;"></span>
        	    </div>
        	    Admin
        	   	</a>
				<ul>
            	  <li>
            	    <%= link_to admin_dashboard_path(:admin_id => "1") do %>
		        	    Manage Users
		            <% end %>
            	  </li>
            	  <li>
            	    <%= link_to admin_analytics_path(:admin_id => "1") do %>
		        	    View Analytics
		            <% end %>
            	  </li>
            	</ul>
            </li>
    	<% end %>
        <li id="benefit_forms">
    <%= link_to user_benefit_forms_path(:user_id => current_user.user_id) do %>
            <div class="icon">
              <span class="fs1" aria-hidden="true" data-icon="&#xe05c;"></span>
            </div>
            Benefit Forms
          <% end %>
        </li>
        <li id="retirement">
           <%= link_to user_retirement_index_path(:user_id => current_user.user_id) do %>
            <div class="icon">
              <span class="fs1" aria-hidden="true" data-icon="&#xe096;"></span>
            </div>
            401k Info
          <% end %>
        </li>
        <li id="pto">
          <%= link_to user_paid_time_off_index_path(:user_id => current_user.user_id) do %>
            <div class="icon">
              <span class="fs1" aria-hidden="true" data-icon="&#xe0d2;"></span>
            </div>
            PTO
         <% end %>
        </li>
        <li id="employee_info">
           <%= link_to user_work_info_index_path(:user_id => current_user.user_id) do %>
            <div class="icon">
              <span class="fs1" aria-hidden="true" data-icon="&#xe0a9;"></span>
            </div>
            Work Info
          <% end %>
        </li>
        <li id="performance">
          <%= link_to user_performance_index_path(:user_id => current_user.user_id) do %>
            <div class="icon">
              <span class="fs1" aria-hidden="true" data-icon="&#xe14a;"></span>
            </div>
            Performance
          <% end %>
        </li>
        <li id="messages">
          <%= link_to user_messages_path(:user_id => current_user.user_id) do %>
            <div class="icon">
              <span class="fs1" aria-hidden="true" data-icon="&#xe040;"></span>
            </div>
            Messages
          <% end %>
        </li>
    <li id="pay">
      <%= link_to user_pay_index_path(:user_id => current_user.user_id) do %>
            <div class="icon">
              <span class="fs1" aria-hidden="true" data-icon="&#xe038;"></span>
            </div>
            Pay
          <% end %>
        </li>
      </ul>
    </div>

  <script type="text/javascript">
  //Main menu navigation

  $('.submenu > a').click(function(e){
    e.preventDefault();
    var submenu = $(this).siblings('ul');
    var li = $(this).parents('li');
    var submenus = $('#mainnav li.submenu ul');
    var submenus_parents = $('#mainnav li.submenu');
    if(li.hasClass('open'))
    {
      if(($(window).width() > 768) || ($(window).width() < 479)) {
        submenu.slideUp();
      } else {
        submenu.fadeOut(250);
      }
      li.removeClass('open');
    } else
    {
      if(($(window).width() > 768) || ($(window).width() < 479)) {
        submenus.slideUp();
        submenu.slideDown();
      } else {
        submenus.fadeOut(250);
        submenu.fadeIn(250);
      }
      submenus_parents.removeClass('open');
      li.addClass('open');
    }
  });

  var ul = $('#mainnav > ul');

  $('#mainnav > a').click(function(e)
  {
    e.preventDefault();
    var mainnav = $('#mainnav');
    if(mainnav.hasClass('open'))
    {
      mainnav.removeClass('open');
      ul.slideUp(250);
    } else
    {
      mainnav.addClass('open');
      ul.slideDown(250);
    }
  });

  </script>
<% end %>